### ISSUE TITLE
Some third-party applications are malfunctioning.

### ISSUE THREAD

**Issue by Code-ANL** [KayleMine/RunAsLimited2#1]
The 3rd party option works broken with GameHelper. I think this is due to GameHelper not being run in its own folder, because GameHelper creates temporary files when it is run, and if these temporary files are not in the folder where GameHelper is located, GameHelper cannot work properly. 

This problem was fixed in previous versions. But it appeared again in the latest version. I would be very grateful if you fix it.

**Comment by KayleMine** [comment]
Fixed:
[Latest](https://github.com/KayleMine/RunAsLimited2/releases/tag/main-1.0)
